version: '3.3'

services:
  app:
    build: .
    container_name: factyble-back
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "12100:12100"
    depends_on:
      - db
    networks:
      - factyble-network

  db:
    image: mysql:latest
    container_name: factyble-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - factyble-network

networks:
  factyble-network:

volumes:
  mysql_data:
