version: '3.3'

services:
  app:
    build: .
    container_name: factyble-back-v2
    restart: always
    env_file:
      - .env
    ports:
      - "${DOCKER_APP_HOST_PORT}:${DOCKER_APP_CONTAINER_PORT}"
    volumes:
      - ./public:/app/public
      - ./logos:/app/logos
      - ./certificados:/app/certificados
    networks:
      - simplifika-network

networks:
  simplifika-network:
    external: true
