-- AlterTable
ALTER TABLE `factura` MODIFY `estado_sifen` ENUM('GENERADO', 'FIRMANDO', 'FIRMADO', 'ENCOLADO', 'ENVIADO', 'APROBADO', 'RECHAZADO', 'ERROR', 'CANCELADO') NULL;

-- AlterTable
ALTER TABLE `nota_credito` MODIFY `estado_sifen` ENUM('GENERADO', 'FIRMANDO', 'FIRMADO', 'ENCOLADO', 'ENVIADO', 'APROBADO', 'RECHAZADO', 'ERROR', 'CANCELADO') NULL;
